### ISSUE TITLE
[FEATURE] Improve the ui design of Create Post

### ISSUE THREAD

**Issue by krishna-nayak** [krishna-nayak/social-space-zone#12]
As you can see, the UI doesn't feel good.
Suggestion - ui:  
<img width="999" alt="Screenshot 2023-08-08 at 8 39 01 PM" src="https://github.com/krishna-nayak/social-space-zone/assets/72739429/24b8be62-b596-4edc-be7e-892aa43ce99a">

**Comment by Sanyam-jain30** [comment]
I have experience in updating UI designs, and I have also understood the issue. Can I please contribute to it?

**Comment by krishna-nayak** [comment]
Sure, go for it. 🚀

**Comment by Sanyam-jain30** [comment]
Thanks a lot.

**Comment by krishna-nayak** [comment]
@Sanyam-jain30  Just make sure to enable the Firebase credential. You can refer to the env-sample file.

**Comment by Sanyam-jain30** [comment]
Yes sure.

**Comment by Sanyam-jain30** [comment]
I am getting an error:
![image](https://github.com/krishna-nayak/social-space-zone/assets/78720027/be57d505-f06b-4b14-bb61-4a3e5bd85c6b)

It is demanding to update the 44 files before committing it. Shall I?

**Comment by krishna-nayak** [comment]
Okay, just run `npm run format` and make sure to add the file to the stage in Git staging and commit.

**Comment by krishna-nayak** [comment]
Look like i need to change this message 🙄🤣.
