### ISSUE TITLE
[BUG] Input Validation for the Create Post 

### ISSUE THREAD

**Issue by krishna-nayak** [krishna-nayak/social-space-zone#8]
Input validation is necessary for the Post input feed, as it accepts data even if it is null.

**Comment by VanshVg** [comment]
Hey, Can I work on this issue?

**Comment by krishna-nayak** [comment]
Sure, go for it. 🚀

**Comment by VanshVg** [comment]
Hey @krishna-nayak Can you please tell me how can I run the project?
I am running npm run dev but on "http://localhost:5173/"  It should open home page according to codebase but It is showing me blank page.

**Comment by krishna-nayak** [comment]
@VanshVg  it seems that you have not configured the Firebase credentials. If you know how to enable Firebase credentials, you are good to go. **If not, just let me know.** 
You can refer to the env-sample file.

**Comment by VanshVg** [comment]
Yeah I can configure it thanx.
